version: '3.8'

services:
  frontend:
    build: ./frontend
    restart: always

  backend:
    build: ./backend
    restart: always

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - frontend
      - backend
    restart: always
